### ISSUE TITLE
SentryLogMiddleware doesn't appear to work with Django 1.9 and Raven 5.27

### ISSUE THREAD

**Issue by tinycogio** [getsentry/raven-python#897]
I've recently noticed that the http/request section has not been showing up for events. After some poking around, I believe it's due to the changes to support Django 1.10 middleware stuff.

Specifically, it looks like it's this line that's failing:
https://github.com/getsentry/raven-python/blob/d5f675be3a3658df6206756183bbd4d192c230cd/raven/contrib/django/client.py#L258

Here is some debugging with ipdb done with the latest version of raven 5.31
```python
ipdb> SentryLogMiddleware.thread
<property object at 0x10f3bb4c8>
ipdb> SentryLogMiddleware.thread.request
*** AttributeError: 'property' object has no attribute 'request'
```
Note that it returns a property object

Here it is again with raven 5.23
```python
ipdb> SentryLogMiddleware.thread
<thread._local object at 0x108a1fd70>
ipdb> SentryLogMiddleware.thread.request
<WSGIRequest: POST '/tapservice/api/'>
```

Looks like 5.26 is the last working version (it stopped working with 5.27)

Packages:
Django==1.9.9
raven==5.31.0
python2.7.x
