### ISSUE TITLE
3.6.0 barfs on timeout query parameter

### ISSUE THREAD

**Issue by moschlar** [getsentry/raven-python#397]
I use the WSGI middleware with a dsn like `http://<...>/3?timeout=5` and since upgrading to 3.6.0, I get

```
2013-12-12 15:52:04,408 ERROR [sentry.errors] Unable to reach Sentry log server: get_transport() got an unexpected keyword argument 'timeout' (url: http://<...>/api/3/store/)
Traceback (most recent call last):
  File "/opt/wsgi/virtualenvs/SAUCE-develop/lib/python2.7/site-packages/raven/base.py", line 544, in send_remote
    parsed, **self.transport_options)
TypeError: get_transport() got an unexpected keyword argument 'timeout'
```
