### ISSUE TITLE
Raven doesn't work with Django 1.10

### ISSUE THREAD

**Issue by piotr-szpetkowski** [getsentry/raven-python#818]
Due to `BaseCommand.option_list` being deprecated in Django 1.8 and finally removed in 1.10 it seems like Raven is rather broken when using new version.

I'm getting following error (easily reproducible):
> AttributeError: type object 'BaseCommand' has no attribute 'option_list'

Steps to reproduce:
1. Create new virtualenv and install Django + raven.
2. Start new project.
3. Configure Raven at settings following docs [@Sentry Docs](https://docs.getsentry.com/hosted/clients/python/integrations/django/)
4. Try to fire up the test management command: `python manage.py raven test`

**Comment by dcramer** [comment]
Considering dropping this functionality entirely since our sys.except_hook handles it now.

**Comment by fengsi** [comment]
`5.24.0` "seems" to support Django 1.10 but test is still not working:
```
$ python manage raven test
AttributeError: type object 'BaseCommand' has no attribute 'option_list'
```

**Comment by dcramer** [comment]
@fengsi ah we missed that one. We'll need to figure out how to support compat there, but at the very least the core integration will be working now.
